In [1]:
# Q1:-
import numpy as np;
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]);

In [2]:
arr = np.random.rand(3, 3);
print(arr);
print(arr.shape);

[[0.99471384 0.71444429 0.71532759]
 [0.78372754 0.02564317 0.49132081]
 [0.10906759 0.89469306 0.27373846]]
(3, 3)


In [3]:
# Q2:-
arr1 = np.array([1.1, 2.2, 3.3], dtype = int);

In [4]:
arr1

array([1, 2, 3])

In [5]:
# Q3:-
arr2 = np.array([1, 2, 3, 4, 5, 6]);

In [6]:
result = arr2[[1, 3, 5]];
print(result);

[2 4 6]


In [7]:
# Q4:-
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]);
matrix = arr4.reshape(3, 3);
print(matrix);

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Q5:-
arr5 = np.array([56, 23, 78, 12, 65, 34]);
result = arr5[arr5 > 50];
print(result);

[56 78 65]
