In [1]:
import numpy as np;

In [2]:
arr = np.array([3, 5, 2, 33, 2, 10]);

In [3]:
np.mean(arr)

np.float64(9.166666666666666)

In [4]:
np.min(arr)

np.int64(2)

In [5]:
np.max(arr)

np.int64(33)

In [6]:
np.std(arr)

np.float64(11.006311320732706)

In [7]:
np.var(arr)

np.float64(121.13888888888891)

In [8]:
np.sum(arr)

np.int64(55)

In [9]:
np.prod(arr)

np.int64(19800)

In [10]:
np.percentile(arr, 50)

np.float64(4.0)

In [11]:
np.argmin(arr)

np.int64(2)

In [12]:
np.argmax(arr)

np.int64(3)

In [13]:
np.corrcoef(arr)

np.float64(1.0)

In [14]:
np.unique(arr)

array([ 2,  3,  5, 10, 33])

In [15]:
np.diff(arr)

array([  2,  -3,  31, -31,   8])

In [16]:
np.diff(arr)

array([  2,  -3,  31, -31,   8])

In [17]:
np.cumsum(arr)

array([ 3,  8, 10, 43, 45, 55])

In [18]:
np.log(arr)

array([1.09861229, 1.60943791, 0.69314718, 3.49650756, 0.69314718,
       2.30258509])

In [19]:
np.exp(arr)

array([2.00855369e+01, 1.48413159e+02, 7.38905610e+00, 2.14643580e+14,
       7.38905610e+00, 2.20264658e+04])